### ISSUE TITLE
Can't post anything

### ISSUE THREAD

**Issue by userj** [turanmahmudov/Instagraph#59]
Device: Mako
Channel: ubports devel
Build: 2019-06-08

Posting a photo doesn't seem to do anything. It looks like it upload, but then the photo never shows up.

**Comment by ItsYanko** [comment]
How you installed the app? snap? openstore🤔🤔?

**Comment by userj** [comment]
Installed from the openstore on ubuntu touch.
Thanks

**Comment by turanmahmudov** [comment]
@userj https://open-store.io/app/instagraph-devs.turan-mahmudov-l can you test it again? It should work now.

**Comment by userj** [comment]
I pressed the "+" button. Sometimes it crashes the app. Sometimes it goes to the camera, but taking a picture makes the shutter sound and nothing happens from there.
I'm now testing on the  pixel 3a (sargo)

**Comment by turanmahmudov** [comment]
@userj yes, I am aware of that. Taking pictures seems don't work for now. I will fix it soon.

**Comment by turanmahmudov** [comment]
@userj it's fixed in v0.1.2.3. The update is live

**Comment by userj** [comment]
Thank you for the quick fix. I was able to post something using the photo from the gallery. Also, it looks like taking pictures works. Sometimes still crashes when pressing the "+" button.

**Comment by turanmahmudov** [comment]
@userj yes, I am aware of that too. I don't know why but pressing the + button on Home page crashes the app.
